"""
Django settings for Pet_Mall project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# 整个项目文件的配置代码
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--=(=5ch&z7e-blmuk7@hh0^&wr&vhbk)3w_^ib===@u7c%$^tm"

# SECURITY WARNING: don't run with debug turned on in production!
# 设置程序出错时的返回（原本开发时出错会在前端显示）
'''如果设置（会显示出错页面：实际投入使用时这样做）
DEBUG = False
ALLOWED_HOSTS = ['本主机地址']
'''
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "PetMallApp.apps.PetmallappConfig"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Pet_Mall.Pet_Mall.urls"

# 相对template文件全局函数以及变量定义
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'PetMallApp/templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "PetMallApp.context_processors.user_session",
            ],
        },
    },
]

WSGI_APPLICATION = "Pet_Mall.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# 数据库为本机8.4版本MySQL中的
DATABASES = {
      'default': {
          'ENGINE': 'django.db.backends.mysql',
          'NAME': 'Pet_Mall',  # 数据库名字
          'USER': 'root',
          'PASSWORD': 'yy0517',
          'HOST': 'localhost',  # 那台机器安装了MySQL，这里设置为本机SQL地址
          'PORT': 3307, #3307端口配置为mysql8.4.0版本
      }
}

# 配置媒体文件绝对路径（为做相对于项目路径铺垫）确保可以通过model模型的ImageField属性值访问图片
MEDIA_URL = '/media/' # 设置全局变量该变量表示项目媒体文件在项目目录下文件夹
# 其中BASE_DIR表示为该项目的绝对地址，拼接上媒体文件目录地址
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# 语言设置
LANGUAGE_CODE = "zh-hans"

# TIME_ZONE = "UTC"
# 时区的修改
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
