# Generated by Django 5.1.4 on 2025-02-09 05:49

import PetMallApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=255, unique=True, verbose_name="订单编号"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单总价"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="订单创建时间"),
                ),
                ("status", models.CharField(max_length=50, verbose_name="订单状态")),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单表",
                "db_table": "Order",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="宠物名")),
                ("age", models.SmallIntegerField(default=0, verbose_name="宠物年龄")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="宠物创建时间"),
                ),
                ("take_offtime", models.DateField(verbose_name="售卖下架时间")),
                ("petlevel", models.SmallIntegerField(default=0, verbose_name="宠物等级")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="领养价格"
                    ),
                ),
                (
                    "special_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="领养特价"
                    ),
                ),
            ],
            options={
                "verbose_name": "宠物信息",
                "verbose_name_plural": "宠物信息表",
                "db_table": "Pet",
            },
        ),
        migrations.CreateModel(
            name="PetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="宠物类型")),
                (
                    "categurs",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="类型描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "宠物类型",
                "verbose_name_plural": "宠物类型表",
                "db_table": "PetCategory",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="宠物销售类型")),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="宠物销售类型描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "宠物销售类型",
                "verbose_name_plural": "宠物销售类型表",
                "db_table": "PetType",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userID",
                    models.CharField(max_length=30, unique=True, verbose_name="用户ID"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="用户名称"
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="用户密码")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女"), (3, "默认")],
                        default=3,
                        verbose_name="用户性别",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="用户邮箱")),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="用户注册时间"),
                ),
                ("last_login", models.DateTimeField(verbose_name="用户最后登陆时间")),
                (
                    "birthday",
                    models.DateTimeField(blank=True, null=True, verbose_name="用户生日"),
                ),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息表",
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单单价"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetMallApp.order",
                        verbose_name="对应订单",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetMallApp.pet",
                        verbose_name="购买宠物产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单详情",
                "verbose_name_plural": "订单详情表",
                "db_table": "OrderDetail",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="petcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="PetMallApp.petcategory",
                verbose_name="宠物类型",
            ),
        ),
        migrations.CreateModel(
            name="PetProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=PetMallApp.models.pet_image_path,
                        verbose_name="宠物展示主图",
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=PetMallApp.models.pet_image_path,
                        verbose_name="宠物展示隐藏图1",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=PetMallApp.models.pet_image_path,
                        verbose_name="宠物展示隐藏图2",
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=PetMallApp.models.pet_image_path,
                        verbose_name="宠物展示隐藏图3",
                    ),
                ),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="PetMallApp.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "宠物展示图",
                "verbose_name_plural": "宠物展示图表",
                "db_table": "PetProfile",
            },
        ),
        migrations.AddField(
            model_name="pet",
            name="ptype",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="PetMallApp.pettype",
                verbose_name="宠物销售类型",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="评分")),
                ("comment", models.TextField(verbose_name="评论")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论创建时间"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetMallApp.pet",
                        verbose_name="被评价产品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetMallApp.user",
                        verbose_name="评价用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客",
                "verbose_name_plural": "博客表",
                "db_table": "Review",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="PetMallApp.user",
                verbose_name="购买用户",
            ),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetMallApp.pet",
                        verbose_name="收藏产品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetMallApp.user",
                        to_field="userID",
                        verbose_name="收藏用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏记录",
                "verbose_name_plural": "收藏记录表",
                "db_table": "Collection",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="购买宠物数量")),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="PetMallApp.pet"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PetMallApp.user",
                        to_field="userID",
                    ),
                ),
            ],
            options={
                "verbose_name": "购物车记录",
                "verbose_name_plural": "购物车记录共用表",
                "db_table": "Cart",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=PetMallApp.models.user_avatar_path,
                        verbose_name="用户头像",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="PetMallApp.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户头像",
                "verbose_name_plural": "用户头像表",
                "db_table": "UserProfile",
            },
        ),
    ]
